
services:
  api:
    build:
      dockerfile: deploy/Dockerfile
      context: ..
      target: ${RUN_ENV:-prod}
    image: open_cec_api:${API_VERSION:-latest}
    restart: always
    # env_file:
    #   - .env
    ports:
      - "${OPEN_CEC_API_PORT:-8080}:${OPEN_CEC_API_PORT:-8080}"
    depends_on:
      - postgres


  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER:-db_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-db_pass}
      POSTGRES_DB: ${DB_NAME:-cec_db}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - ${DB_PORT:-5432}:${DB_PORT:-5432}
    restart: unless-stopped
  

volumes:
    postgres:
